version: "3"
services:
  api: 
    build: .
    ports:
      - "3000:3000"
    env_file: dev.env
    environment:
      CACHE_SERVER: cache
      CACHE_PORT: 6379
      CACHE_PREFIX: ''
    volumes:
      - .:/usr/src/app
  cache:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
    
      